FROM node
 LABEL maintainer printerprof@yandex.ru
 RUN git clone -q https://github.com/DavyRoy/test_deploy/tree/main/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B8%D0%B9%20%D1%81%D1%82%D0%BE%D0%BB/Docker-tesr/test.git 
 WORKDIR Docker-tesr
 RUN npm install > /dev/null
 EXPOSE 8000
 CMD ["npm","start"]
