version: '3.7'

services:
  document_api:
    build: .
    container_name: document_api
    ports:
      - 8002:8000
    networks:
      - default
      - gen_dev
    hostname: document-api
    environment:
      DEBUG: 1
      SECRET_KEY: "k(#wgcv4oxag+64w&-t5+ziepw8dhgy=_pq!yhds$r^uhdji(d"
      DATABASE_URI: "postgres://softgenesis:ldFLf5G6gDpb@master.f8cfe68e-0f6a-4326-a609-67c17231882a.c.dbaas.selcloud.ru:6432/document_api_db?sslmode=verify-ca"
    volumes:
      - ./coverage_reports:/usr/share/coverage_reports
      - /root/.postgresql:/root/.postgresql
    command: bash -c "
      cd /usr/srv/document_api/src &&
      python3 manage.py migrate &&
      python3 manage.py auto_create_super_user &&
      uvicorn document_api.asgi:application --host 0.0.0.0 --port 8000
      "

networks:
  gen_dev:
    external: true
