# Generated by Django 4.0.1 on 2022-04-07 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('activity', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=55)),
                ('updated_by', models.CharField(blank=True, max_length=55, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_document', models.CharField(max_length=255)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('is_archive', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=55)),
                ('updated_by', models.CharField(blank=True, max_length=55, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.typedocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
