# Generated by Django 4.0.1 on 2022-04-04 14:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=55, null=True)),
                ('created_by', models.CharField(max_length=55)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2555)),
                ('executor', models.CharField(max_length=255)),
                ('observers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=20)),
                ('priority', models.IntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')])),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Processing'), (2, 'On pause'), (3, 'On review'), (4, 'Returned'), (5, 'Finished')])),
                ('started_at', models.DateTimeField()),
                ('planned_ended_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=55, null=True)),
                ('created_by', models.CharField(max_length=55)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=2555)),
                ('executor', models.CharField(max_length=255)),
                ('reviewers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=20)),
                ('observers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=20)),
                ('responsible', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=20)),
                ('priority', models.IntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')])),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Processing'), (2, 'On pause'), (3, 'On review'), (4, 'Returned'), (5, 'Finished')])),
                ('type', models.IntegerField(choices=[(0, 'Issue'), (1, 'Assignment'), (2, 'Agreement'), (3, 'SOS')])),
                ('is_selected_reviewer', models.BooleanField(default=False)),
                ('is_task_agreement', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('planned_ended_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('check_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gen_task.checkpoint')),
                ('previous_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_task.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=55, null=True)),
                ('created_by', models.CharField(max_length=55)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_id', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_files', to='gen_task.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=55, null=True)),
                ('created_by', models.CharField(max_length=55)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='gen_task.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=55, null=True)),
                ('created_by', models.CharField(max_length=55)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=3000)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='gen_task.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
