# Generated by Django 4.0.1 on 2022-04-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='is_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='gen_task.checkpoint'),
        ),
        migrations.AlterField(
            model_name='task',
            name='check_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gen_task.checkpoint'),
        ),
    ]
