# Generated by Django 4.0.1 on 2022-04-26 11:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAnalyticData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('processing', models.DateTimeField(blank=True, null=True)),
                ('on_pause', models.DateTimeField(blank=True, null=True)),
                ('on_review', models.DateTimeField(blank=True, null=True)),
                ('returned', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('agreed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='notification_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Processing'), (2, 'On pause'), (3, 'On review'), (4, 'Returned'), (5, 'Agreed'), (6, 'Finished')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Processing'), (2, 'On pause'), (3, 'On review'), (4, 'Returned'), (5, 'Agreed'), (6, 'Finished')]),
        ),
        migrations.AddField(
            model_name='task',
            name='task_analytic_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='gen_task.taskanalyticdata'),
        ),
    ]
