# Generated by Django 4.0.1 on 2022-04-20 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0003_remove_commenttask_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=20),
        ),
    ]
