# Generated by Django 4.0.1 on 2022-05-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0002_task_analytic_data'),
        ('gen_task', '0005_change_task_ordering'),
    ]

    operations = [
    ]
