# Generated by Django 4.0.1 on 2022-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0006_merge_20220523_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='executor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
