# Generated by Django 4.0.1 on 2022-05-24 17:35

from django.db import migrations, models
import django.db.models.deletion


def apply_task_analytic_data(apps, schema_editor):
    Task = apps.get_model('gen_task.Task')
    TaskAnalyticData = apps.get_model('gen_task.TaskAnalyticData')
    tasks = list(Task.objects.all())
    for task in tasks:
        task.task_analytic_data = TaskAnalyticData.objects.create()
    Task.objects.bulk_update(tasks, ['task_analytic_data'])


def reverse_dummy(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0007_sub_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_analytic_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='gen_task.taskanalyticdata'),
        ),


        migrations.RunPython(
            apply_task_analytic_data,
            reverse_code=reverse_dummy
        )

    ]
