# Generated by Django 4.0.1 on 2022-07-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0008_alter_task_task_analytic_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttask',
            name='is_system_comment',
            field=models.BooleanField(default=False),
        ),
    ]
