# Generated by Django 4.0.1 on 2022-07-21 08:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0009_history_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='check_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gen_task.checkpoint', verbose_name='Контрольная точка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=2555, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.CharField(max_length=255, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_selected_reviewer',
            field=models.BooleanField(default=False, verbose_name='Вернуть на проверку'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_task_agreement',
            field=models.BooleanField(default=False, verbose_name='Создать задачу на согласование'),
        ),
        migrations.AlterField(
            model_name='task',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=20, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notification_owner',
            field=models.BooleanField(default=False, verbose_name='Уведомлять создателя'),
        ),
        migrations.AlterField(
            model_name='task',
            name='observers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=20, verbose_name='Наблюдатели'),
        ),
        migrations.AlterField(
            model_name='task',
            name='planned_ended_at',
            field=models.DateTimeField(verbose_name='Планируемая дата окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='previous_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_task.task', verbose_name='Предыдущая Задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')], verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=20, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=20, verbose_name='Аудиторы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Processing'), (2, 'On pause'), (3, 'On review'), (4, 'Returned'), (5, 'Agreed'), (6, 'Finished')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(0, 'Issue'), (1, 'Assignment'), (2, 'Agreement'), (3, 'SOS')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
