# Generated by Django 4.0.1 on 2022-07-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0010_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_tasks', to='gen_task.task', verbose_name='Следующая Задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='previous_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_tasks', to='gen_task.task', verbose_name='Предыдущая Задача'),
        ),
    ]
