# Generated by Django 4.0.1 on 2022-07-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0012_verbose_name_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект'),
        ),
    ]
