# Generated by Django 4.0.1 on 2022-08-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0013_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file_id',
            field=models.CharField(max_length=2555),
        ),
    ]
