# Generated by Django 4.0.1 on 2022-09-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_task', '0014_task_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Processing'), (2, 'On pause'), (3, 'On review'), (4, 'Returned'), (5, 'Agreed'), (6, 'Finished'), (7, 'Archived')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Processing'), (2, 'On pause'), (3, 'On review'), (4, 'Returned'), (5, 'Agreed'), (6, 'Finished'), (7, 'Archived')], verbose_name='Статус'),
        ),
    ]
